### ISSUE TITLE
[[import using cloud shell]]

### ISSUE THREAD

**Issue by supcik** [googlecodelabs/cloud-grpc#11]
At the end of the second slide, there is link to "using cloud shell". This link points to a Google Drive that requires special permission.

![screen_dump_2017-03-05_09-02-25_am](https://cloud.githubusercontent.com/assets/30344/23585584/97ef1920-0182-11e7-9f24-62b80a4725e7.png)

Perhaps "**import**" should be bold (according to the [Codelab Formatting Guide](https://docs.google.com/document/d/18dnMdUJQaGKY1Tit_-fO1YOpOpAbA4hh0YDXQlCEjvA/edit?ts=574ec5d9#heading=h.azwb0t5t0e91))

**Comment by thesandlord** [comment]
Working now, the Google Drive doc's permissions have been fixed
