### ISSUE TITLE
Step 4: Get the sample - undefined

### ISSUE THREAD

**Issue by Indavelopers** [googlecodelabs/cloud-grpc#12]
After running "go run client.go" as requested, output is:
books/books.pb.go:107: undefined: grpc.SupportPackageIsVersion3

Current dir: "~/cloud-grpc/start"
"go get google.golang.org/grpc" in previous step did not return nothing, assumed ok.

**Comment by thesandlord** [comment]
Fixed: https://github.com/googlecodelabs/cloud-grpc/pull/14
