### ISSUE TITLE
books.pb.go needs to be regenerated

### ISSUE THREAD

**Issue by MakMukhi** [googlecodelabs/cloud-grpc#6]
Hey,

We recently updated the grpc code and the protoc generator thereby rendering grpc.SupportPackageIsVersion3 obsolete. This will cause compile-time problems. Regenerating books.pb.go should work.
Under books dir run: protoc -I . books.proto --go_out=plugins=grpc:. 

Thanks

**Comment by jab** [comment]
Thanks for opening this @MakMukhi!

Once the maintainers fix it this time, is there some way they can make sure it doesn't happen in the future, assuming that's possible? (e.g. Could a future update to grpc ever cause a change like `const _ = grpc.SupportPackageIsVersion5` which would result in this breaking again?)

**Comment by MakMukhi** [comment]
Unfortunately, yes that might happen. Usually a project would regenerate
their proto files at compile time. Give, this is a code lab they have
provided the generated code to make things easier. But, this brings the
onus of updating the code with changes to grpc code base (or provide
instructions on how to do that).

**Comment by markmandel** [comment]
This seems to be fine now. Please re-open if it becomes an issue again.
