### ISSUE TITLE
s/grpc.Credentials/grpc.credentials

### ISSUE THREAD

**Issue by jab** [googlecodelabs/cloud-grpc#8]
On https://codelabs.developers.google.com/codelabs/cloud-grpc/index.html?index=..%2F..%2Findex#8 one of the excerpts of client.js includes
```js
var client = new booksProto.books.BookService('127.0.0.1:50051', 
  grpc.Credentials.createInsecure());
```
This causes
```
/Users/<user>/src/cloud-grpc/start/client.js:6
  grpc.Credentials.createInsecure());
                  ^
TypeError: Cannot read property 'createInsecure' of undefined
```
Replacing `grpc.Credentials` with `grpc.credentials` fixes this.

**Comment by markmandel** [comment]
This has been fixed via #15
